<?php
/**
 * Grp_Inquiry extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Grp
 * @package        Grp_Inquiry
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Inquiry comments list template
 *
 * @category    Grp
 * @package     Grp_Inquiry
 * @author      Grapes-solutions.com
 */
?>
<?php $_inquiry = $this->getInquiry()?>
<?php if ($_inquiry->getAllowComments()) : ?>
    <?php $_comments = $this->getComments(); ?>
    <?php if (count($_comments)) : ?>
        <div class="box-collateral box-reviews" id="inquiry-reviews">
            <h2><?php echo $this->__('Comments for: %s', $_inquiry->getInquiries()) ?></h2>
            <?php echo $this->getPagerHtml() ?>
            <dl>
                <?php foreach ($_comments as $_comment):?>
                <dt>
                    <div class="author"><?php echo $this->__('On %s %s wrote:', $this->formatDate($_comment->getCreatedAt(), 'long'), $this->htmlEscape($_comment->getName()))?></div>
                    <strong><?php echo $this->htmlEscape($_comment->getTitle()) ?></strong>
                </dt>
                <dd>
                    <?php echo nl2br($this->htmlEscape($_comment->getComment())) ?>
                </dd>
                <?php endforeach; ?>
            </dl>
            <?php echo $this->getPagerHtml() ?>
        </div>
    <?php endif;?>
    <?php echo $this->getChildHtml('comment_form') ?>
<?php endif;?>
